[[constraint]]
  name = "github.com/urfave/cli"
  version = "v1.20.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.1"

[[constraint]]
  name = "github.com/kylelemons/godebug"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true